[email]
host = "smtp.123.com:465"
username = "username"
password = "password"

[auth]
algorithm = "HS256"
secret_key = "FuCubeMC-API"

[database]
ip = "loacalhost"
username = "username"
password = "password"
name = "panel"

[links]
main = "http://0.0.0.0"